services:
  storeuiapp:
    container_name: storeuiappcontainer
    build: .
    image: storeuiapp:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
